### ISSUE TITLE
Unable to use FileCreateTransaction() in index.js file

### ISSUE THREAD

**Issue by Ashok-Sandhyala** [ed-marquez/hedera-example-contract-getter-setter#1]
I could not able to use FileCreateTransaction() in the index file and it is throwing 'not defined'
<img width="390" alt="Hedera_error2" src="https://user-images.githubusercontent.com/83112805/181216444-026316b4-8f15-4625-a39c-068c7ecdff8b.png">
<img width="293" alt="Hedera_Errors1" src="https://user-images.githubusercontent.com/83112805/181216455-dd4ab3ea-3291-4979-aa02-95ef2652d6ae.png">

**Comment by ed-marquez** [comment]
FileCreateTransaction() is a module that should be imported from the SDK. Looks like you're not importing that module.

For ease and reference, consider this same example in code sandbox:
https://codesandbox.io/s/hedera-example-contract-getter-setter-8whrs?file=/index.js:2870-2871

Or consider following the tutorial:
https://hedera.com/blog/how-to-deploy-smart-contracts-on-hedera-part-1-a-simple-getter-and-setter-contract
